# Generated by Django 4.2.8 on 2025-12-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Yoga Ganesha', max_length=200, verbose_name='Nombre del Negocio')),
                ('phone', models.CharField(default='+34 123 456 789', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(default='info@yogaganesha.com', max_length=254, verbose_name='Email')),
                ('address', models.TextField(default='Villena, Alicante, España', verbose_name='Dirección')),
                ('schedule', models.CharField(default='Lun - Vie: 8:00 - 20:00', max_length=100, verbose_name='Horario')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/yogaghanesa.villena.9/?locale=es_ES', verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/yogaganeshavillena/', verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='Twitter')),
                ('whatsapp_number', models.CharField(blank=True, default='+34123456789', max_length=20, verbose_name='WhatsApp')),
                ('hero_title', models.CharField(default='Cambia Tu Vida Con Yoga y Meditación', max_length=200, verbose_name='Título Principal')),
                ('hero_subtitle', models.TextField(default='El yoga es una gran práctica tanto para el cuerpo como para la mente.', verbose_name='Subtítulo Principal')),
                ('about_title', models.CharField(default='Sobre Nosotros', max_length=200, verbose_name='Título Sobre Nosotros')),
                ('about_text', models.TextField(default='Bienvenido a Yoga Ganesha', verbose_name='Texto Sobre Nosotros')),
            ],
            options={
                'verbose_name': 'Configuración del Negocio',
                'verbose_name_plural': 'Configuración del Negocio',
            },
        ),
    ]
