# Generated by Django 4.2.8 on 2025-12-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video de YouTube')], default='image', max_length=10, verbose_name='Tipo')),
                ('image', models.ImageField(blank=True, help_text='Sube una imagen desde tu dispositivo', null=True, upload_to='gallery/', verbose_name='Imagen')),
                ('youtube_url', models.URLField(blank=True, help_text='Ej: https://www.youtube.com/watch?v=VIDEO_ID', verbose_name='URL de YouTube')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Elemento de Galería',
                'verbose_name_plural': 'Galería',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
