# Generated by Django 4.2.8 on 2025-12-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='notification_email',
            field=models.EmailField(blank=True, default='info@yogaganesha.com', help_text='Email donde recibirás las notificaciones de contacto', max_length=254, verbose_name='Email para Notificaciones'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='send_email_notifications',
            field=models.BooleanField(default=False, help_text='Activar para recibir emails cuando alguien use el formulario de contacto', verbose_name='Enviar Notificaciones por Email'),
        ),
    ]
