# Generated by Django 4.2.8 on 2025-12-12 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('period', models.CharField(default='mes', help_text='Ej: mes, año', max_length=50, verbose_name='Período')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('features', models.TextField(help_text='Una característica por línea', verbose_name='Características')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Plan Popular')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Plan de Precios',
                'verbose_name_plural': 'Planes de Precios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Profesión')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto')),
                ('testimonial_text', models.TextField(verbose_name='Testimonio')),
                ('rating', models.IntegerField(default=5, help_text='De 1 a 5 estrellas', verbose_name='Calificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('excerpt', models.TextField(help_text='Resumen breve del post', max_length=300, verbose_name='Extracto')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen Destacada')),
                ('category', models.CharField(default='General', max_length=100, verbose_name='Categoría')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post del Blog',
                'verbose_name_plural': 'Posts del Blog',
                'ordering': ['-published_date'],
            },
        ),
    ]
