# Generated by Django 4.2.8 on 2025-12-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('pilates', 'Pilates Yoga'), ('hatha', 'Hatha Yoga'), ('vinyasa', 'Vinyasa Yoga'), ('iyengar', 'Iyengar Yoga'), ('ashtanga', 'Ashtanga Yoga'), ('kundalini', 'Kundalini Yoga'), ('yin', 'Yin Yoga'), ('bikram', 'Bikram Yoga')], max_length=50, verbose_name='Categoría')),
                ('image', models.ImageField(blank=True, null=True, upload_to='classes/', verbose_name='Imagen')),
                ('schedule_days', models.CharField(help_text='Ej: Lun, Mié, Vie', max_length=100, verbose_name='Días')),
                ('schedule_time', models.CharField(help_text='Ej: 9:00 - 10:00', max_length=50, verbose_name='Horario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructors.instructor', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Clase de Yoga',
                'verbose_name_plural': 'Clases de Yoga',
                'ordering': ['order', 'name'],
            },
        ),
    ]
