# Generated by Django 4.2.8 on 2026-02-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Disciplina / Categoría',
                'verbose_name_plural': 'Disciplinas / Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='yogaclass',
            name='instructor',
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='classes', to='instructors.instructor', verbose_name='Instructores'),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.classcategory', verbose_name='Disciplina/Categoría'),
        ),
    ]
