# Generated by Django 4.2.8 on 2026-02-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classcategory_remove_yogaclass_instructor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Subtítulo')),
                ('date_text', models.CharField(help_text='Ej: 15 de Marzo, 2024', max_length=100, verbose_name='Fecha Texto')),
                ('image', models.ImageField(help_text='Imagen grande para el carrusel', upload_to='events/', verbose_name='Imagen de Fondo')),
                ('button_text', models.CharField(default='MÁS INFORMACIÓN', max_length=50, verbose_name='Texto del Botón')),
                ('button_link', models.CharField(default='#', help_text='URL o ancla (ej: /classes/ o #contact)', max_length=255, verbose_name='Enlace del Botón')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Evento / Carrusel',
                'verbose_name_plural': 'Eventos / Carrusel',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
